# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c02de5b986381f5afbd3a0974dc40a6fe5fdb7cb63ee92a5197bda4411a820b35e64e777af68660c6fa3d68932312fd7fa1fd5f15692b76b7b718f20666861ca

test:
  secret_key_base: 0f6070db8151d557d10397bdf1ed4d280270cafd737f2181836ee42b726dd2557107ccd1a58c395bed169a170760a9bdc24f0a8454121732710766ae606c5db4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
